# version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo_user
      - POSTGRES_PASSWORD=2400
      - POSTGRES_DB=odoo_db
    networks:
      - odoo-net
  odoo:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - .:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo_user
      - PASSWORD=2400
    command: --dev=reload --log-level=debug --database=odoo_db --db_host=db --db_user=odoo_user --db_password=2400 --init=base
    networks:
      - odoo-net

  doc_reader:
    build: ./doc_reader
    ports:
      - "8000:8000"
    volumes:
      - ./doc_reader:/app
      - ./doc_reader/credentials:/app/credentials
    environment:
      - PYTHONPATH=/app
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/gcp.json
    networks:
      - odoo-net
    restart: unless-stopped
networks:
  odoo-net:
    name: odoo-net